### ISSUE TITLE
no viable alternative at input '[sst-2,'

### ISSUE THREAD

**Issue by JosueLin** [UCF-ML-Research/TrojLLM#2]
I tried running the following command in the PromptSeed directory:python run_fsc.py     dataset=[sst-2, yelp-2, mr, cr, agnews]     dataset_seed=[0, 1, 2, 3, 4]     prompt_length=[5]     task_lm=[distilroberta-base, roberta-base, roberta-large,              distilgpt2, gpt2, gpt2-medium, gpt2-large, gpt2-xl]     random_seed=[0]

An error occurred:no viable alternative at input '[sst-2,'

**Comment by jqxue1999** [comment]
Thanks for your interest on our work. I have uploaded other datasets, you could use other alternative datasets now.
